<?php
/**
 * @version $Header: /cvsroot/bitweaver/_bit_address/admin/schema_inc.php,v 1.1 2009/09/23 15:16:44 spiderr Exp $
 * @package address
 */
global $gBitInstaller;
require_once(ADDRESS_PKG_PATH.'BitAddress.php');
require_once(ADDRESS_PKG_PATH.'BitAddressCountry.php');

$gBitInstaller->registerPackageInfo(ADDRESS_PKG_NAME, array(
	'description' => "This package is to store and manipulate location address data.",
	'license' => '<a href="http://www.gnu.org/licenses/licenses.html#LGPL">LGPL</a>',
));

// Get definition of DB tables used by this packages objects.
$tables = array_merge(
	BitAddress::getSchemaTables(),
	BitAddressCountry::getSchemaTables()
);

foreach(array_keys($tables) AS $tableName) {
	$gBitInstaller->registerSchemaTable(ADDRESS_PKG_NAME, $tableName, $tables[$tableName]);
}

// $indices = array();
// $gBitInstaller->registerSchemaIndexes(ADDRESS_PKG_NAME, $indices);

// Sequences
$gBitInstaller->registerSchemaSequences(ADDRESS_PKG_NAME, array_merge(
	BitAddress::getSchemaSequences(),
	BitAddressCountry::getSchemaSequences()
));

$country_table = BIT_DB_PREFIX.BitAddressCountry::DATA_TBL;
$fields_table = BIT_DB_PREFIX.BitAddress::FIELDS_TBL;
// Schema defaults
$gBitInstaller->registerSchemaDefault(ADDRESS_PKG_NAME, array(
"INSERT INTO `".$country_table."` VALUES(1,'Afghanistan', 'AF', 'AFG', '4', 'y')",
"INSERT INTO `".$country_table."` VALUES(2,'Albania', 'AL', 'ALB', '8', 'y')",
"INSERT INTO `".$country_table."` VALUES(3,'Algeria', 'DZ', 'DZA', '12', 'y')",
"INSERT INTO `".$country_table."` VALUES(4,'American Samoa', 'AS', 'ASM', '16', 'y')",
"INSERT INTO `".$country_table."` VALUES(5,'Andorra', 'AD', 'AND', '20', 'y')",
"INSERT INTO `".$country_table."` VALUES(6,'Angola', 'AO', 'AGO', '24', 'y')",
"INSERT INTO `".$country_table."` VALUES(7,'Anguilla', 'AI', 'AIA', '660', 'y')",
"INSERT INTO `".$country_table."` VALUES(8,'Antarctica', 'AQ', 'ATA', '10', 'y')",
"INSERT INTO `".$country_table."` VALUES(9,'Antigua and Barbuda', 'AG', 'ATG', '28', 'y')",
"INSERT INTO `".$country_table."` VALUES(10,'Argentina', 'AR', 'ARG', '32', 'y')",
"INSERT INTO `".$country_table."` VALUES(11,'Armenia', 'AM', 'ARM', '51', 'y')",
"INSERT INTO `".$country_table."` VALUES(12,'Aruba', 'AW', 'ABW', '533', 'y')",
"INSERT INTO `".$country_table."` VALUES(13,'Australia', 'AU', 'AUS', '36', 'y')",
"INSERT INTO `".$country_table."` VALUES(14,'Austria', 'AT', 'AUT', '40', 'y')",
"INSERT INTO `".$country_table."` VALUES(15,'Azerbaijan', 'AZ', 'AZE', '31', 'y')",
"INSERT INTO `".$country_table."` VALUES(16,'Bahamas', 'BS', 'BHS', '44', 'y')",
"INSERT INTO `".$country_table."` VALUES(17,'Bahrain', 'BH', 'BHR', '48', 'y')",
"INSERT INTO `".$country_table."` VALUES(18,'Bangladesh', 'BD', 'BGD', '50', 'y')",
"INSERT INTO `".$country_table."` VALUES(19,'Barbados', 'BB', 'BRB', '52', 'y')",
"INSERT INTO `".$country_table."` VALUES(20,'Belarus', 'BY', 'BLR', '112', 'y')",
"INSERT INTO `".$country_table."` VALUES(21,'Belgium', 'BE', 'BEL', '56', 'y')",
"INSERT INTO `".$country_table."` VALUES(22,'Belize', 'BZ', 'BLZ', '84', 'y')",
"INSERT INTO `".$country_table."` VALUES(23,'Benin', 'BJ', 'BEN', '204', 'y')",
"INSERT INTO `".$country_table."` VALUES(24,'Bermuda', 'BM', 'BMU', '60', 'y')",
"INSERT INTO `".$country_table."` VALUES(25,'Bhutan', 'BT', 'BTN', '64', 'y')",
"INSERT INTO `".$country_table."` VALUES(26,'Bolivia', 'BO', 'BOL', '68', 'y')",
"INSERT INTO `".$country_table."` VALUES(27,'Bosnia and Herzegowina', 'BA', 'BIH', '70', 'y')",
"INSERT INTO `".$country_table."` VALUES(28,'Botswana', 'BW', 'BWA', '72', 'y')",
"INSERT INTO `".$country_table."` VALUES(29,'Bouvet Island', 'BV', 'BVT', '74', 'y')",
"INSERT INTO `".$country_table."` VALUES(30,'Brazil', 'BR', 'BRA', '76', 'y')",
"INSERT INTO `".$country_table."` VALUES(31,'British Indian Ocean Territory', 'IO', 'IOT', '86', 'y')",
"INSERT INTO `".$country_table."` VALUES(32,'Brunei Darussalam', 'BN', 'BRN', '96', 'y')",
"INSERT INTO `".$country_table."` VALUES(33,'Bulgaria', 'BG', 'BGR', '100', 'y')",
"INSERT INTO `".$country_table."` VALUES(34,'Burkina Faso', 'BF', 'BFA', '854', 'y')",
"INSERT INTO `".$country_table."` VALUES(35,'Burundi', 'BI', 'BDI', '108', 'y')",
"INSERT INTO `".$country_table."` VALUES(36,'Cambodia', 'KH', 'KHM', '116', 'y')",
"INSERT INTO `".$country_table."` VALUES(37,'Cameroon', 'CM', 'CMR', '120', 'y')",
"INSERT INTO `".$country_table."` VALUES(38,'Canada', 'CA', 'CAN', '124', 'y')",
"INSERT INTO `".$country_table."` VALUES(39,'Cape Verde', 'CV', 'CPV', '132', 'y')",
"INSERT INTO `".$country_table."` VALUES(40,'Cayman Islands', 'KY', 'CYM', '136', 'y')",
"INSERT INTO `".$country_table."` VALUES(41,'Central African Republic', 'CF', 'CAF', '140', 'y')",
"INSERT INTO `".$country_table."` VALUES(42,'Chad', 'TD', 'TCD', '148', 'y')",
"INSERT INTO `".$country_table."` VALUES(43,'Chile', 'CL', 'CHL', '152', 'y')",
"INSERT INTO `".$country_table."` VALUES(44,'China', 'CN', 'CHN', '156', 'y')",
"INSERT INTO `".$country_table."` VALUES(45,'Christmas Island', 'CX', 'CXR', '162', 'y')",
"INSERT INTO `".$country_table."` VALUES(46,'Cocos (Keeling) Islands', 'CC', 'CCK', '166', 'y')",
"INSERT INTO `".$country_table."` VALUES(47,'Colombia', 'CO', 'COL', '170', 'y')",
"INSERT INTO `".$country_table."` VALUES(48,'Comoros', 'KM', 'COM', '174', 'y')",
"INSERT INTO `".$country_table."` VALUES(49,'Congo', 'CG', 'COG', '178', 'y')",
"INSERT INTO `".$country_table."` VALUES(50,'Cook Islands', 'CK', 'COK', '184', 'y')",
"INSERT INTO `".$country_table."` VALUES(51,'Costa Rica', 'CR', 'CRI', '188', 'y')",
"INSERT INTO `".$country_table."` VALUES(52,'Cote D''Ivoire', 'CI', 'CIV', '384', 'y')",
"INSERT INTO `".$country_table."` VALUES(53,'Croatia', 'HR', 'HRV', '191', 'y')",
"INSERT INTO `".$country_table."` VALUES(55,'Cyprus', 'CY', 'CYP', '196', 'y')",
"INSERT INTO `".$country_table."` VALUES(54,'Cuba', 'CU', 'CUB', '203', 'y')",
"INSERT INTO `".$country_table."` VALUES(56,'Czech Republic', 'CZ', 'CZE', '203', 'y')",
"INSERT INTO `".$country_table."` VALUES(57,'Denmark', 'DK', 'DNK', '208', 'y')",
"INSERT INTO `".$country_table."` VALUES(58,'Djibouti', 'DJ', 'DJI', '262', 'y')",
"INSERT INTO `".$country_table."` VALUES(59,'Dominica', 'DM', 'DMA', '212', 'y')",
"INSERT INTO `".$country_table."` VALUES(60,'Dominican Republic', 'DO', 'DOM', '214', 'y')",
"INSERT INTO `".$country_table."` VALUES(61,'East Timor', 'TP', 'TMP', '626', 'y')",
"INSERT INTO `".$country_table."` VALUES(62,'Ecuador', 'EC', 'ECU', '218', 'y')",
"INSERT INTO `".$country_table."` VALUES(63,'Egypt', 'EG', 'EGY', '818', 'y')",
"INSERT INTO `".$country_table."` VALUES(64,'El Salvador', 'SV', 'SLV', '222', 'y')",
"INSERT INTO `".$country_table."` VALUES(65,'Equatorial Guinea', 'GQ', 'GNQ', '226', 'y')",
"INSERT INTO `".$country_table."` VALUES(66,'Eritrea', 'ER', 'ERI', '232', 'y')",
"INSERT INTO `".$country_table."` VALUES(67,'Estonia', 'EE', 'EST', '233', 'y')",
"INSERT INTO `".$country_table."` VALUES(68,'Ethiopia', 'ET', 'ETH', '231', 'y')",
"INSERT INTO `".$country_table."` VALUES(69,'Falkland Islands (Malvinas)', 'FK', 'FLK', '238', 'y')",
"INSERT INTO `".$country_table."` VALUES(70,'Faroe Islands', 'FO', 'FRO', '234', 'y')",
"INSERT INTO `".$country_table."` VALUES(71,'Fiji', 'FJ', 'FJI', '242', 'y')",
"INSERT INTO `".$country_table."` VALUES(72,'Finland', 'FI', 'FIN', '246', 'y')",
"INSERT INTO `".$country_table."` VALUES(74,'France, Metropolitan', 'FX', 'FXX', '249', 'y')",
"INSERT INTO `".$country_table."` VALUES(73,'France', 'FR', 'FRA', '250', 'y')",
"INSERT INTO `".$country_table."` VALUES(75,'French Guiana', 'GF', 'GUF', '254', 'y')",
"INSERT INTO `".$country_table."` VALUES(76,'French Polynesia', 'PF', 'PYF', '258', 'y')",
"INSERT INTO `".$country_table."` VALUES(77,'French Southern Territories', 'TF', 'ATF', '260', 'y')",
"INSERT INTO `".$country_table."` VALUES(78,'Gabon', 'GA', 'GAB', '266', 'y')",
"INSERT INTO `".$country_table."` VALUES(79,'Gambia', 'GM', 'GMB', '270', 'y')",
"INSERT INTO `".$country_table."` VALUES(80,'Georgia', 'GE', 'GEO', '268', 'y')",
"INSERT INTO `".$country_table."` VALUES(81,'Germany', 'DE', 'DEU', '276', 'y')",
"INSERT INTO `".$country_table."` VALUES(82,'Ghana', 'GH', 'GHA', '288', 'y')",
"INSERT INTO `".$country_table."` VALUES(83,'Gibraltar', 'GI', 'GIB', '292', 'y')",
"INSERT INTO `".$country_table."` VALUES(84,'Greece', 'GR', 'GRC', '300', 'y')",
"INSERT INTO `".$country_table."` VALUES(85,'Greenland', 'GL', 'GRL', '304', 'y')",
"INSERT INTO `".$country_table."` VALUES(86,'Grenada', 'GD', 'GRD', '308', 'y')",
"INSERT INTO `".$country_table."` VALUES(87,'Guadeloupe', 'GP', 'GLP', '312', 'y')",
"INSERT INTO `".$country_table."` VALUES(88,'Guam', 'GU', 'GUM', '316', 'y')",
"INSERT INTO `".$country_table."` VALUES(89,'Guatemala', 'GT', 'GTM', '320', 'y')",
"INSERT INTO `".$country_table."` VALUES(90,'Guinea', 'GN', 'GIN', '324', 'y')",
"INSERT INTO `".$country_table."` VALUES(91,'Guinea-bissau', 'GW', 'GNB', '624', 'y')",
"INSERT INTO `".$country_table."` VALUES(92,'Guyana', 'GY', 'GUY', '328', 'y')",
"INSERT INTO `".$country_table."` VALUES(93,'Haiti', 'HT', 'HTI', '332', 'y')",
"INSERT INTO `".$country_table."` VALUES(94,'Heard and Mc Donald Islands', 'HM', 'HMD', '334', 'y')",
"INSERT INTO `".$country_table."` VALUES(95,'Honduras', 'HN', 'HND', '340', 'y')",
"INSERT INTO `".$country_table."` VALUES(96,'Hong Kong', 'HK', 'HKG', '344', 'y')",
"INSERT INTO `".$country_table."` VALUES(97,'Hungary', 'HU', 'HUN', '348', 'y')",
"INSERT INTO `".$country_table."` VALUES(98,'Iceland', 'IS', 'ISL', '352', 'y')",
"INSERT INTO `".$country_table."` VALUES(99,'India', 'IN', 'IND', '356', 'y')",
"INSERT INTO `".$country_table."` VALUES(100,'Indonesia', 'ID', 'IDN', '360', 'y')",
"INSERT INTO `".$country_table."` VALUES(101,'Iran (Islamic Republic of)', 'IR', 'IRN', '364', 'y')",
"INSERT INTO `".$country_table."` VALUES(102,'Iraq', 'IQ', 'IRQ', '368', 'y')",
"INSERT INTO `".$country_table."` VALUES(103,'Ireland', 'IE', 'IRL', '372', 'y')",
"INSERT INTO `".$country_table."` VALUES(104,'Israel', 'IL', 'ISR', '376', 'y')",
"INSERT INTO `".$country_table."` VALUES(105,'Italy', 'IT', 'ITA', '380', 'y')",
"INSERT INTO `".$country_table."` VALUES(106,'Jamaica', 'JM', 'JAM', '388', 'y')",
"INSERT INTO `".$country_table."` VALUES(107,'Japan', 'JP', 'JPN', '392', 'y')",
"INSERT INTO `".$country_table."` VALUES(108,'Jordan', 'JO', 'JOR', '400', 'y')",
"INSERT INTO `".$country_table."` VALUES(109,'Kazakhstan', 'KZ', 'KAZ', '398', 'y')",
"INSERT INTO `".$country_table."` VALUES(110,'Kenya', 'KE', 'KEN', '404', 'y')",
"INSERT INTO `".$country_table."` VALUES(111,'Kiribati', 'KI', 'KIR', '296', 'y')",
"INSERT INTO `".$country_table."` VALUES(112,'Korea, Democratic People''s Republic of', 'KP', 'PRK', '408', 'y')",
"INSERT INTO `".$country_table."` VALUES(113,'Korea, Republic of', 'KR', 'KOR', '410', 'y')",
"INSERT INTO `".$country_table."` VALUES(114,'Kuwait', 'KW', 'KWT', '414', 'y')",
"INSERT INTO `".$country_table."` VALUES(115,'Kyrgyzstan', 'KG', 'KGZ', '417', 'y')",
"INSERT INTO `".$country_table."` VALUES(116,'Lao People''s Democratic Republic', 'LA', 'LAO', '418', 'y')",
"INSERT INTO `".$country_table."` VALUES(117,'Latvia', 'LV', 'LVA', '428', 'y')",
"INSERT INTO `".$country_table."` VALUES(118,'Lebanon', 'LB', 'LBN', '422', 'y')",
"INSERT INTO `".$country_table."` VALUES(119,'Lesotho', 'LS', 'LSO', '426', 'y')",
"INSERT INTO `".$country_table."` VALUES(120,'Liberia', 'LR', 'LBR', '430', 'y')",
"INSERT INTO `".$country_table."` VALUES(121,'Libyan Arab Jamahiriya', 'LY', 'LBY', '434', 'y')",
"INSERT INTO `".$country_table."` VALUES(122,'Liechtenstein', 'LI', 'LIE', '438', 'y')",
"INSERT INTO `".$country_table."` VALUES(123,'Lithuania', 'LT', 'LTU', '440', 'y')",
"INSERT INTO `".$country_table."` VALUES(124,'Luxembourg', 'LU', 'LUX', '442', 'y')",
"INSERT INTO `".$country_table."` VALUES(125,'Macau', 'MO', 'MAC', '446', 'y')",
"INSERT INTO `".$country_table."` VALUES(126,'Macedonia, The Former Yugoslav Republic of', 'MK', 'MKD', '807', 'y')",
"INSERT INTO `".$country_table."` VALUES(127,'Madagascar', 'MG', 'MDG', '450', 'y')",
"INSERT INTO `".$country_table."` VALUES(128,'Malawi', 'MW', 'MWI', '454', 'y')",
"INSERT INTO `".$country_table."` VALUES(129,'Malaysia', 'MY', 'MYS', '458', 'y')",
"INSERT INTO `".$country_table."` VALUES(130,'Maldives', 'MV', 'MDV', '462', 'y')",
"INSERT INTO `".$country_table."` VALUES(131,'Mali', 'ML', 'MLI', '466', 'y')",
"INSERT INTO `".$country_table."` VALUES(132,'Malta', 'MT', 'MLT', '470', 'y')",
"INSERT INTO `".$country_table."` VALUES(133,'Marshall Islands', 'MH', 'MHL', '584', 'y')",
"INSERT INTO `".$country_table."` VALUES(134,'Martinique', 'MQ', 'MTQ', '474', 'y')",
"INSERT INTO `".$country_table."` VALUES(135,'Mauritania', 'MR', 'MRT', '478', 'y')",
"INSERT INTO `".$country_table."` VALUES(136,'Mauritius', 'MU', 'MUS', '480', 'y')",
"INSERT INTO `".$country_table."` VALUES(137,'Mayotte', 'YT', 'MYT', '175', 'y')",
"INSERT INTO `".$country_table."` VALUES(138,'Mexico', 'MX', 'MEX', '484', 'y')",
"INSERT INTO `".$country_table."` VALUES(139,'Micronesia, Federated States of', 'FM', 'FSM', '583', 'y')",
"INSERT INTO `".$country_table."` VALUES(140,'Moldova, Republic of', 'MD', 'MDA', '498', 'y')",
"INSERT INTO `".$country_table."` VALUES(141,'Monaco', 'MC', 'MCO', '492', 'y')",
"INSERT INTO `".$country_table."` VALUES(142,'Mongolia', 'MN', 'MNG', '496', 'y')",
"INSERT INTO `".$country_table."` VALUES(143,'Montserrat', 'MS', 'MSR', '500', 'y')",
"INSERT INTO `".$country_table."` VALUES(144,'Morocco', 'MA', 'MAR', '504', 'y')",
"INSERT INTO `".$country_table."` VALUES(145,'Mozambique', 'MZ', 'MOZ', '508', 'y')",
"INSERT INTO `".$country_table."` VALUES(146,'Myanmar', 'MM', 'MMR', '104', 'y')",
"INSERT INTO `".$country_table."` VALUES(147,'Namibia', 'NA', 'NAM', '516', 'y')",
"INSERT INTO `".$country_table."` VALUES(148,'Nauru', 'NR', 'NRU', '520', 'y')",
"INSERT INTO `".$country_table."` VALUES(149,'Nepal', 'NP', 'NPL', '524', 'y')",
"INSERT INTO `".$country_table."` VALUES(150,'Netherlands', 'NL', 'NLD', '528', 'y')",
"INSERT INTO `".$country_table."` VALUES(151,'Netherlands Antilles', 'AN', 'ANT', '530', 'y')",
"INSERT INTO `".$country_table."` VALUES(152,'New Caledonia', 'NC', 'NCL', '540', 'y')",
"INSERT INTO `".$country_table."` VALUES(153,'New Zealand', 'NZ', 'NZL', '554', 'y')",
"INSERT INTO `".$country_table."` VALUES(154,'Nicaragua', 'NI', 'NIC', '558', 'y')",
"INSERT INTO `".$country_table."` VALUES(155,'Niger', 'NE', 'NER', '562', 'y')",
"INSERT INTO `".$country_table."` VALUES(156,'Nigeria', 'NG', 'NGA', '566', 'y')",
"INSERT INTO `".$country_table."` VALUES(157,'Niue', 'NU', 'NIU', '570', 'y')",
"INSERT INTO `".$country_table."` VALUES(158,'Norfolk Island', 'NF', 'NFK', '574', 'y')",
"INSERT INTO `".$country_table."` VALUES(159,'Northern Mariana Islands', 'MP', 'MNP', '580', 'y')",
"INSERT INTO `".$country_table."` VALUES(160,'Norway', 'NO', 'NOR', '578', 'y')",
"INSERT INTO `".$country_table."` VALUES(161,'Oman', 'OM', 'OMN', '512', 'y')",
"INSERT INTO `".$country_table."` VALUES(162,'Pakistan', 'PK', 'PAK', '586', 'y')",
"INSERT INTO `".$country_table."` VALUES(163,'Palau', 'PW', 'PLW', '585', 'y')",
"INSERT INTO `".$country_table."` VALUES(164,'Panama', 'PA', 'PAN', '591', 'y')",
"INSERT INTO `".$country_table."` VALUES(165,'Papua New Guinea', 'PG', 'PNG', '598', 'y')",
"INSERT INTO `".$country_table."` VALUES(166,'Paraguay', 'PY', 'PRY', '600', 'y')",
"INSERT INTO `".$country_table."` VALUES(167,'Peru', 'PE', 'PER', '604', 'y')",
"INSERT INTO `".$country_table."` VALUES(168,'Philippines', 'PH', 'PHL', '608', 'y')",
"INSERT INTO `".$country_table."` VALUES(169,'Pitcairn', 'PN', 'PCN', '612', 'y')",
"INSERT INTO `".$country_table."` VALUES(170,'Poland', 'PL', 'POL', '616', 'y')",
"INSERT INTO `".$country_table."` VALUES(171,'Portugal', 'PT', 'PRT', '620', 'y')",
"INSERT INTO `".$country_table."` VALUES(172,'Puerto Rico', 'PR', 'PRI', '630', 'y')",
"INSERT INTO `".$country_table."` VALUES(173,'Qatar', 'QA', 'QAT', '634', 'y')",
"INSERT INTO `".$country_table."` VALUES(174,'Reunion', 'RE', 'REU', '638', 'y')",
"INSERT INTO `".$country_table."` VALUES(175,'Romania', 'RO', 'ROM', '642', 'y')",
"INSERT INTO `".$country_table."` VALUES(176,'Russian Federation', 'RU', 'RUS', '643', 'y')",
"INSERT INTO `".$country_table."` VALUES(177,'Rwanda', 'RW', 'RWA', '646', 'y')",
"INSERT INTO `".$country_table."` VALUES(178,'Saint Kitts and Nevis', 'KN', 'KNA', '659', 'y')",
"INSERT INTO `".$country_table."` VALUES(179,'Saint Lucia', 'LC', 'LCA', '662', 'y')",
"INSERT INTO `".$country_table."` VALUES(180,'Saint Vincent and the Grenadines', 'VC', 'VCT', '670', 'y')",
"INSERT INTO `".$country_table."` VALUES(181,'Samoa', 'WS', 'WSM', '882', 'y')",
"INSERT INTO `".$country_table."` VALUES(182,'San Marino', 'SM', 'SMR', '674', 'y')",
"INSERT INTO `".$country_table."` VALUES(183,'Sao Tome and Principe', 'ST', 'STP', '678', 'y')",
"INSERT INTO `".$country_table."` VALUES(184,'Saudi Arabia', 'SA', 'SAU', '682', 'y')",
"INSERT INTO `".$country_table."` VALUES(185,'Senegal', 'SN', 'SEN', '686', 'y')",
"INSERT INTO `".$country_table."` VALUES(186,'Seychelles', 'SC', 'SYC', '690', 'y')",
"INSERT INTO `".$country_table."` VALUES(187,'Sierra Leone', 'SL', 'SLE', '694', 'y')",
"INSERT INTO `".$country_table."` VALUES(188,'Singapore', 'SG', 'SGP', '702', 'y')",
"INSERT INTO `".$country_table."` VALUES(189,'Slovakia (Slovak Republic)', 'SK', 'SVK', '703', 'y')",
"INSERT INTO `".$country_table."` VALUES(190,'Slovenia', 'SI', 'SVN', '705', 'y')",
"INSERT INTO `".$country_table."` VALUES(191,'Solomon Islands', 'SB', 'SLB', '90', 'y')",
"INSERT INTO `".$country_table."` VALUES(192,'Somalia', 'SO', 'SOM', '706', 'y')",
"INSERT INTO `".$country_table."` VALUES(193,'South Africa', 'ZA', 'ZAF', '710', 'y')",
"INSERT INTO `".$country_table."` VALUES(194,'South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239', 'y')",
"INSERT INTO `".$country_table."` VALUES(195,'Spain', 'ES', 'ESP', '724', 'y')",
"INSERT INTO `".$country_table."` VALUES(196,'Sri Lanka', 'LK', 'LKA', '144', 'y')",
"INSERT INTO `".$country_table."` VALUES(197,'St. Helena', 'SH', 'SHN', '654', 'y')",
"INSERT INTO `".$country_table."` VALUES(198,'St. Pierre and Miquelon', 'PM', 'SPM', '666', 'y')",
"INSERT INTO `".$country_table."` VALUES(199,'Sudan', 'SD', 'SDN', '736', 'y')",
"INSERT INTO `".$country_table."` VALUES(200,'Suriname', 'SR', 'SUR', '740', 'y')",
"INSERT INTO `".$country_table."` VALUES(201,'Svalbard and Jan Mayen Islands', 'SJ', 'SJM', '744', 'y')",
"INSERT INTO `".$country_table."` VALUES(202,'Swaziland', 'SZ', 'SWZ', '748', 'y')",
"INSERT INTO `".$country_table."` VALUES(203,'Sweden', 'SE', 'SWE', '752', 'y')",
"INSERT INTO `".$country_table."` VALUES(204,'Switzerland', 'CH', 'CHE', '756', 'y')",
"INSERT INTO `".$country_table."` VALUES(205,'Syrian Arab Republic', 'SY', 'SYR', '760', 'y')",
"INSERT INTO `".$country_table."` VALUES(206,'Taiwan', 'TW', 'TWN', '158', 'y')",
"INSERT INTO `".$country_table."` VALUES(207,'Tajikistan', 'TJ', 'TJK', '762', 'y')",
"INSERT INTO `".$country_table."` VALUES(208,'Tanzania, United Republic of', 'TZ', 'TZA', '834', 'y')",
"INSERT INTO `".$country_table."` VALUES(209,'Thailand', 'TH', 'THA', '764', 'y')",
"INSERT INTO `".$country_table."` VALUES(210,'Togo', 'TG', 'TGO', '768', 'y')",
"INSERT INTO `".$country_table."` VALUES(211,'Tokelau', 'TK', 'TKL', '772', 'y')",
"INSERT INTO `".$country_table."` VALUES(212,'Tonga', 'TO', 'TON', '776', 'y')",
"INSERT INTO `".$country_table."` VALUES(213,'Trinidad and Tobago', 'TT', 'TTO', '780', 'y')",
"INSERT INTO `".$country_table."` VALUES(214,'Tunisia', 'TN', 'TUN', '788', 'y')",
"INSERT INTO `".$country_table."` VALUES(215,'Turkey', 'TR', 'TUR', '792', 'y')",
"INSERT INTO `".$country_table."` VALUES(216,'Turkmenistan', 'TM', 'TKM', '795', 'y')",
"INSERT INTO `".$country_table."` VALUES(217,'Turks and Caicos Islands', 'TC', 'TCA', '796', 'y')",
"INSERT INTO `".$country_table."` VALUES(218,'Tuvalu', 'TV', 'TUV', '798', 'y')",
"INSERT INTO `".$country_table."` VALUES(219,'Uganda', 'UG', 'UGA', '800', 'y')",
"INSERT INTO `".$country_table."` VALUES(220,'Ukraine', 'UA', 'UKR', '804', 'y')",
"INSERT INTO `".$country_table."` VALUES(221,'United Arab Emirates', 'AE', 'ARE', '784', 'y')",
"INSERT INTO `".$country_table."` VALUES(222,'United Kingdom', 'GB', 'GBR', '826', 'y')",
"INSERT INTO `".$country_table."` VALUES(223,'United States', 'US', 'USA', '840', 'y')",
"INSERT INTO `".$country_table."` VALUES(224,'United States Minor Outlying Islands', 'UM', 'UMI', '581', 'y')",
"INSERT INTO `".$country_table."` VALUES(225,'Uruguay', 'UY', 'URY', '858', 'y')",
"INSERT INTO `".$country_table."` VALUES(226,'Uzbekistan', 'UZ', 'UZB', '860', 'y')",
"INSERT INTO `".$country_table."` VALUES(227,'Vanuatu', 'VU', 'VUT', '548', 'y')",
"INSERT INTO `".$country_table."` VALUES(228,'Vatican City State (Holy See)', 'VA', 'VAT', '336', 'y')",
"INSERT INTO `".$country_table."` VALUES(229,'Venezuela', 'VE', 'VEN', '862', 'y')",
"INSERT INTO `".$country_table."` VALUES(230,'Viet Nam', 'VN', 'VNM', '704', 'y')",
"INSERT INTO `".$country_table."` VALUES(231,'Virgin Islands (British)', 'VG', 'VGB', '92', 'y')",
"INSERT INTO `".$country_table."` VALUES(232,'Virgin Islands (U.S.)', 'VI', 'VIR', '850', 'y')",
"INSERT INTO `".$country_table."` VALUES(233,'Wallis and Futuna Islands', 'WF', 'WLF', '876', 'y')",
"INSERT INTO `".$country_table."` VALUES(234,'Western Sahara', 'EH', 'ESH', '732', 'y')",
"INSERT INTO `".$country_table."` VALUES(235,'Yemen', 'YE', 'YEM', '887', 'y')",
"INSERT INTO `".$country_table."` VALUES(237,'Zaire', 'ZR', 'ZAR', '180', 'y')",
"INSERT INTO `".$country_table."` VALUES(238,'Zambia', 'ZM', 'ZMB', '894', 'y')",
"INSERT INTO `".$country_table."` VALUES(239,'Zimbabwe', 'ZW', 'ZWE', '716', 'y')",
// FIELDS_TBL: fieldname, country_id, description, helptext, type, typopt, maxlen, options, defval, is_required, rule
"INSERT INTO `".$fields_table."` VALUES('postcode',0,'Postal Code','Country assigned code for address (ZIP, postcode, ...)','text','',16,'','','n','')",
"INSERT INTO `".$fields_table."` VALUES('region',0,'Region','Area of country for address (State, County, ...)','text','',64,'','','n','')",
"INSERT INTO `".$fields_table."` VALUES('town',0,'Town/City','Name of urban area address located in','text','',64,'','','n','')",
"INSERT INTO `".$fields_table."` VALUES('street2',0,'Street Extra','Any additional location data','text','',64,'','','n','')",
"INSERT INTO `".$fields_table."` VALUES('street1',0,'Street Address','Location name/number and street name','text','',64,'','','n','')",
"INSERT INTO `".$fields_table."` VALUES('type_bits',0,'Location Type','Uses of this location','text','',0,'','','n','Business,Home')",
"INSERT INTO `".$fields_table."` VALUES('delivery_bits',0,'Delivery Options','Types of delivery accepted at location','text','',0,'','','n','Carrier,Post')",
"INSERT INTO `".$fields_table."` VALUES('postcode',222,'Postcode','UK postal code, 5-8 alphanumerics with space in middle','text','',16,'','','n','')",
"INSERT INTO `".$fields_table."` VALUES('postcode',223,'ZIP code','US postal code, 5digits followed by optional -4digits','text','',16,'','','n','')",
"INSERT INTO `".$fields_table."` VALUES('region',222,'County','UK Postal County name','text','',64,'','','n','')",
"INSERT INTO `".$fields_table."` VALUES('region',223,'State','US State, as 2 letter abbreviation or in full','text','',64,'','','n','')",
"INSERT INTO `".$fields_table."` VALUES('town',222,'Town','Town or City locality name in the UK','text','',64,'','','n','')",
"INSERT INTO `".$fields_table."` VALUES('town',223,'City','Name of urban area in the US','text','',64,'','','n','')",
));

// User Permissions
$gBitInstaller->registerUserPermissions(ADDRESS_PKG_NAME, array(
	array('p_address_admin',   'Can admin address',            'admin',      ADDRESS_PKG_NAME),
	array('p_address_update',  'Can update any address entry', 'editors',    ADDRESS_PKG_NAME),
	array('p_address_create',  'Can create a address entry',   'registered', ADDRESS_PKG_NAME),
	array('p_address_view',    'Can view address data',        'basic',      ADDRESS_PKG_NAME),
	array('p_address_expunge', 'Can delete any address entry', 'admin',      ADDRESS_PKG_NAME),
));

// Default Preferences
$gBitInstaller->registerPreferences(ADDRESS_PKG_NAME, array(
	array(ADDRESS_PKG_NAME, 'address_default_ordering', 'address_id_desc'),
	array(ADDRESS_PKG_NAME, 'address_list_country',     'y'),
	array(ADDRESS_PKG_NAME, 'address_list_description', 'y'),
	array(ADDRESS_PKG_NAME, 'address_country_default',  223), // USA - see above
));

// Version - now use upgrades dir to set package version number.
// $gBitInstaller->registerPackageVersion( ADDRESS_PKG_NAME, '0.1.0' );

// Requirements
$gBitInstaller->registerRequirements( ADDRESS_PKG_NAME, array(
	'liberty' => array( 'min' => '2.1.0' ),
	'libertyform' => array( 'min' => '0.1.0' ),
	'kernel' => array( 'min' => '2.0.0' ),
	'themes' => array( 'min' => '2.0.0' ),
	'languages' => array( 'min' => '2.0.0' ),
));
?>
